# Generated by Django 3.1.4 on 2021-01-14 14:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('Position', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodels')),
            ],
        ),
    ]
