# Generated by Django 3.1.4 on 2021-01-14 16:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210114_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodels',
            name='parent',
        ),
        migrations.AddField(
            model_name='staffmodels',
            name='position',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='staff.staffmodels'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
