# Generated by Django 3.1.4 on 2021-01-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210114_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmodels',
            old_name='position',
            new_name='parent',
        ),
    ]
