# Generated by Django 3.1.4 on 2021-01-14 16:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210114_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmodels',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='staffmodels',
            old_name='FIO',
            new_name='name',
        ),
        migrations.AddField(
            model_name='staffmodels',
            name='position',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodels',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staff.staffmodels'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
