# Generated by Django 3.1.4 on 2021-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210114_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodels',
            name='salary_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodels',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
