# Generated by Django 3.1.4 on 2021-01-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20210117_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodels',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
