# Generated by Django 3.1.4 on 2021-01-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staffmodels_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodels',
            name='object_id',
        ),
    ]
